from .patchnr import PatchNR
from .epll import EPLL
from .CNN_prior import CNNPrior
from .wcrr import WCRR
from .NETT_prior import NETT
from .tdv import TDV
from .lpn.lpn import LPNPrior
from .local_ar import LocalAR
from .simple_ICNN import simple_ICNNPrior
from .LSR import LSR
from .parameter_learning_wrapper import ParameterLearningWrapper
from .simple_IDCNN_prior import simple_IDCNNPrior
